<?php

function og_services_permission() {
  return array(
    'og service import create' => array(
      'title' => t('OG Services Create OG Entry'),
      'description' => t('OG Services Create OG Entry.'),
    ),
    'og service import delete' => array(
      'title' => t('OG Services Delete OG Entry'),
      'description' => t('OG Services Delete OG Entry.'),
    ),
  );
}

/**
 * Implements hook_services_resources().
 */
function og_services_services_resources() {
  return array(
    'og' => array(
        'create' => array(
          'help' => 'Creates an OG membership entry',
          'file' => array('type' => 'inc', 'module' => 'og_services', 'name' => 'og_services'),
          'callback' => '_og_services_create',
          'access callback' => '_og_services_access',
          'access arguments' => array('create'),
          'args' => array(
            array(
              'name' => 'data',
              'type' => 'struct',
              'description' => 'The membership object',
              'source' => 'data',
              'optional' => FALSE,
            ),
          ),
        ),
        'delete' => array(
          'help' => 'Deletes an OG membership entries based on User UUID and Node UUID combination',
          'file' => array('type' => 'inc', 'module' => 'og_services', 'name' => 'og_services'),
          'callback' => '_og_services_delete',
          'access callback' => '_og_services_access',
          'access arguments' => array('delete'),
          'args' => array(
            array(
              'name' => 'id',
              'type' => 'int',
              'description' => 'The id of the GROUP to update',
              'source' => array('path' => '0'),
              'optional' => FALSE,
            ),
          ),
        ),
      ),
  );
}


/**
 * Access check callback for file controllers.
 */

function _og_services_access($op = 'view', $args = array()) {
  switch ($op) {
    case 'view': // NOT USED
      return FALSE;
    break;
    case 'create':
      if(user_access('og service import create')) {
        return TRUE;
      } else {
        return FALSE;
      }
    break;
    case 'delete':
      if(user_access('og service import delete')) {
        return TRUE;
      } else {
        return FALSE;
      }
    break;
    case 'index': // NOT USED
      return FALSE;
    break;
  }

  return FALSE;
}



//end